// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/default/body.vue')['default']
    'Config.ce': typeof import('./src/components/shadow/config.ce.vue')['default']
    'Element.ce': typeof import('./src/components/shadow/element.ce.vue')['default']
    Header: typeof import('./src/components/shadow/header.vue')['default']
    'Header.ce': typeof import('./src/components/shadow/header.ce.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Platefrom: typeof import('./src/components/default/platefrom.vue')['default']
    Platform: typeof import('./src/components/default/platform.vue')['default']
    SuperDrag: typeof import('./src/components/default/superDrag.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
